name: Test

on:
  - push
  - pull_request

env:
  ENDBOT_CI_TOKEN: ${{ secrets.ENDBOT_CI_TOKEN }}
  ENDBOT_CI_GUILD: ${{ secrets.ENDBOT_CI_GUILD }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run tests
      run: npm test
